### ISSUE TITLE
Bug in rpc get_messages with embedded newlines

### ISSUE THREAD

**Issue by lumenano** [TheCircleFoundation/concealx#4]
When the cli simple wallet is started with rpc activated by specifying a port in the command line, most requests work but not get_messages when the Reply-To was used to create a message using the gui wallet (the simple wallet doesn't allow message creation and the gui wallet doesn't seem to have an rpc server). A JSON error is returned.

The problem is that when a message is created with the gui wallet and the option to include a reply-to address in the message, the address plus two newlines is prepended to the message. The JSON response will actually include two newlines rather than \n\n, which is not allowed. This may be a general problem with any message that includes embedded newlines, unless each line is treated as a separate message (I didn't check into this). The JSON serializer is unable to parse the embedded newlines.

To get get_messages working, I just hacked src/Wallet/WalletRpcServer.cpp by inserting the following at line 230 in function bool wallet_rpc_server::on_get_messages()

```
for (auto it = tx_messages.messages.begin(); it != tx_messages.messages.end(); it++) {
  for (std::string::size_type n = 0; ( ( n = (*it).find("\n", n ) ) != std::string::npos ); ) {
    (*it).replace(n, 1, "\\n");
    n += 2;
  }
}

```
All this does is replace newlines with \n in each message in the list of messages before they are converted to a JSON response. Now, the RPC get_messages works, which is what I need right now.

Another way to fix this problem would be attach the reply-to address as a separate message, and to also not allow general messages to have embedded newlines but rather split lines into separate messages (each transaction is allowed a list of separate messages). Perhaps the latter rule is already in effect and the problem is only with the way reply-to is handled. I haven't looked at that part of the code.

**Comment by krypt0x** [comment]
Closed

**Comment by lumenano** [comment]
Is there a patch for this?
